### ISSUE TITLE
check and clean doesn't work with 134 samples

### ISSUE THREAD

**Issue by sawibo** [UMCUGenetics/IAP#110]
When running IAP with 134 samples, check and clean is not able to run because of a too long argument list in qsub (see below):

_###SCHEDULING CHECK AND CLEAN####
Can't exec "qsub": Argument list too long at /hpc/local/CentOS7/cog_bioinf/IAP_v2.6.0/IAP/check.pm line 353._

Is this fixable ?

**Comment by inijman** [comment]
Does the rest of the pipeline run ok?

**Comment by sawibo** [comment]
I'll give an update as soon as the rest of the jobs have finished/failed.

**Comment by rernst** [comment]
What is the status of this?
