### ISSUE TITLE
Improvements / rewrites

### ISSUE THREAD

**Issue by rernst** [UMCUGenetics/IAP#38]
This issue is meant as a log / note an things we would like to improve in later versions of the IAP, but are not code / pipeline breaking bugs or new features. 
- [ ] BWA mapping, view, sort using pipes and no compression.
- [ ] Rewrite and/or structure config checking. Although very flexible, the current method is laborious to update and maintain. #36 
- [ ] Move duplicate code, to separate function and / or module. For example, jobid and qsub functions.
- [ ] getting rid of "hack" in illumina_poststats.pm. #31 (Currently not possible)

**Comment by jdeligt** [comment]
Is dit nog steeds relevant? Anders misschien closen
